version: '3.7'

#网络配置
networks:
  net:
    external: true
    # 实际指向的网络连接
    name: bas-ws-net

services: 
  thupat-ms:
    image: unitrack/thupat-ms
    restart: always
    container_name: thu-thupat-ms
    networks:
      net:
    volumes:
      - /etc/localtime:/etc/localtime
      # 日志目录
      - ./app/logs:/app/logs
      - ./app/config.yml:/app/config.yml
      # 程序文件（程序已打包，可以不设置）
      - ./app/thupat-ms-0.0.1-fat.jar:/app/thupat-ms.jar
